
services:

  db:
    image: postgres:16

    container_name: inventory_db

    restart: always

    env_file:
      - ./backend/.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:

    build:
      context: ./backend

    container_name: inventory_backend

    restart: always

    env_file:
      - ./backend/.env

    depends_on:
      - db

    ports:
      - "5000:5000"

  frontend:

    build:
      context: ./frontend

    container_name: inventory_frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  postgres_data:

